return {
    LeftBar = {
        {
            MaxWidth = 700,
            Scale = {1.2,1}
        },
        {
            MaxWidth = 900,
            Scale = {.7,1}
        },
        {
            MaxWidth = 1100,
            Scale = {.6,1}
        },
        {
            MaxWidth = math.huge,
            Scale = {.5,1}
        }
    },
    WeaponInfo = {
        {
            MaxWidth = 700,
            Scale = {1,1}
        },
        {
            MaxWidth = 900,
            Scale = {.8,.8}
        },
        {
            MaxWidth = 1100,
            Scale = {.65,.65}
        },
        {
            MaxWidth = math.huge,
            Scale = {.5,.5}
        }
    }
}