return {
    LeftBar = {
        {
            MaxWidth = 700,
            Scale = {1.2,1}
        },
        {
            MaxWidth = 900,
            Scale = {.7,1}
        },
        {
            MaxWidth = 1100,
            Scale = {.6,1}
        },
        {
            MaxWidth = math.huge,
            Scale = {.5,1}
        }
    },
    WeaponInfo = {
        {
            MaxWidth = 700,
            Scale = {1,1}
        },
        {
            MaxWidth = 900,
            Scale = {.75,.75}
        },
        {
            MaxWidth = 1100,
            Scale = {.6,.6}
        },
        {
            MaxWidth = math.huge,
            Scale = {.45,.45}
        }
    },
    Guns = {
        {
            MaxWidth = 900,
            Scale = {.7,.7}
        },  
        {
            MaxWidth = math.huge,
            Scale = {.45,.45}   
        }
    },
    Shop = {
        {
            MaxWidth = 900,
            Scale = {.7,.7}
        },  
        {
            MaxWidth = math.huge,
            Scale = {.45,.45}
        }
    }
}